version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/nginx-logs:/var/log/nginx
    environment:
      - ENABLE_IPV6=true
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets-encrypt
    depends_on:
      - "nginx-proxy"
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
  web-huannv:
    image: huannv93/cv:latest
    depends_on:
      - "letsencrypt"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=huannguyen7651.info
      - LETSENCRYPT_HOST=huannguyen7651.info
      - LETSENCRYPT_EMAIL=huannguyen7651.info

volumes:
  certs:
  html:
  vhost:
  dhparam: